//! # D-Bus interface proxy for: `ca.kamacite.BootEnvironment`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/ca/kamacite/BootEnvironments/2282eba6cadb22c3' from service 'ca.kamacite.BootEnvironments1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "ca.kamacite.BootEnvironment",
    default_service = "ca.kamacite.BootEnvironments1",
    default_path = "/ca/kamacite/BootEnvironments/2282eba6cadb22c3"
)]
pub trait BootEnvironment {
    /// Activate method
    fn activate(&self, temporary: bool) -> zbus::Result<()>;

    /// Describe method
    fn describe(&self, description: &str) -> zbus::Result<()>;

    /// Destroy method
    fn destroy(&self, force_unmount: bool, snapshots: bool) -> zbus::Result<()>;

    /// DestroySnapshot method
    fn destroy_snapshot(&self, snapshot: &str) -> zbus::Result<()>;

    /// GetSnapshots method
    #[allow(clippy::type_complexity)]
    fn get_snapshots(&self) -> zbus::Result<Vec<(String, String, String, u64, i64)>>;

    /// Mount method
    fn mount(&self, mountpoint: &str, read_only: bool) -> zbus::Result<()>;

    /// Rename method
    fn rename(&self, new_name: &str) -> zbus::Result<()>;

    /// Rollback method
    fn rollback(&self, snapshot: &str) -> zbus::Result<()>;

    /// Snapshot method
    fn snapshot(&self, snapshot_name: &str, description: &str) -> zbus::Result<String>;

    /// Unmount method
    fn unmount(&self, force: bool) -> zbus::Result<String>;

    /// Active property
    #[zbus(property)]
    fn active(&self) -> zbus::Result<bool>;

    /// BootOnce property
    #[zbus(property)]
    fn boot_once(&self) -> zbus::Result<bool>;

    /// Created property
    #[zbus(property)]
    fn created(&self) -> zbus::Result<i64>;

    /// Description property
    #[zbus(property)]
    fn description(&self) -> zbus::Result<String>;

    /// Guid property
    #[zbus(property)]
    fn guid(&self) -> zbus::Result<u64>;

    /// Mountpoint property
    #[zbus(property)]
    fn mountpoint(&self) -> zbus::Result<String>;

    /// Name property
    #[zbus(property)]
    fn name(&self) -> zbus::Result<String>;

    /// NextBoot property
    #[zbus(property)]
    fn next_boot(&self) -> zbus::Result<bool>;

    /// Root property
    #[zbus(property)]
    fn root(&self) -> zbus::Result<String>;

    /// Space property
    #[zbus(property)]
    fn space(&self) -> zbus::Result<u64>;
}
